import { chromium } from 'playwright';
import { createRequire } from 'node:module';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const axe=readFileSync(require.resolve('axe-core/axe.min.js'),'utf8');
const base=process.env.PROTOTYPE_URL??'http://127.0.0.1:5176';
const root=new URL('./',import.meta.url).pathname;
mkdirSync(root+'screenshots',{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH??'/usr/bin/chromium',args:['--no-sandbox']});
const errors=[],external=[];let scenes=0,scans=0,shots=0;
const rows={AFTER:['SHIFT_DOWN','CHECK_IN','WORKOUT','MAIN_SLEEP'],BEFORE:['TONIGHT','FUEL'],SHIFT:['QUICK_LOG','FUEL'],OFF:['CHECK_IN','WORKOUT'],TRAINING:['CHECK_IN','WORKOUT'],UNKNOWN:['WORK_QUESTION','CHECK_IN','WORKOUT']};
async function open(width=360,story='AFTER',reading='GREEN',extra=''){
 const context=await browser.newContext({viewport:{width,height:915},reducedMotion:extra==='reduced'?'reduce':'no-preference'});
 await context.addInitScript(()=>{for(const name of ['localStorage','sessionStorage','indexedDB'])Object.defineProperty(window,name,{get(){throw Error('Forbidden storage access: '+name)}});if(navigator.serviceWorker)navigator.serviceWorker.register=()=>{throw Error('Forbidden service worker registration')};});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('data:'))external.push(r.url());});
 await page.goto(`${base}/?story=${story}&reading=${reading}${extra.startsWith('tab=')?'&'+extra:''}`);await page.locator('.mission,.feature').waitFor();await page.evaluate(()=>document.fonts.ready);return {page,context};
}
async function layout(page){assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Horizontal page overflow');const bad=await page.locator('button,summary,input,select,textarea,a').evaluateAll(es=>es.filter(e=>{const r=e.getBoundingClientRect();return r.width&&r.height&&(r.width<44||r.height<44)}).map(e=>e.outerHTML));assert.deepEqual(bad,[],'Small targets');}
async function accessibility(page){await page.addScriptTag({content:axe});const result=await page.evaluate(async()=>await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));assert.deepEqual(result.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),[]);scans++;}
async function shot(page,name,fullPage=true){await page.screenshot({path:root+'screenshots/'+name+'.png',fullPage});shots++;}
try{
 for(const width of [320,360,412])for(const story of Object.keys(rows))for(const reading of ['GREEN','AMBER','RED','NO_READ']){
  const {page,context}=await open(width,story,reading);await layout(page);assert.deepEqual(await page.locator('[data-phase-row]').evaluateAll(es=>es.map(e=>e.dataset.phaseRow)),rows[story]);assert.equal(await page.locator('.phase-path [aria-current]').count(),story==='UNKNOWN'?0:1);assert.equal(await page.locator('.intelligence').getAttribute('open'),null);assert(await page.locator('.status-reading').innerText().then(t=>t.includes(reading.replace('_',' '))));assert.equal(await page.locator('.context').evaluate(e=>getComputedStyle(e).borderLeftColor==='rgb(208, 20, 27)'),reading==='RED');assert(await page.locator('.mission[data-primary="true"]').count()<=1);
  if(width===360)await accessibility(page);
  if(story==='AFTER'||story==='UNKNOWN'&&reading==='NO_READ'){if(story==='AFTER'&&reading!=='NO_READ')await shot(page,`today-${reading.toLowerCase()}-${width}`);if(story==='UNKNOWN')await shot(page,`today-unknown-${width}`);}
  if(story==='AFTER'&&reading==='GREEN'){await page.locator('.intelligence>summary').focus();await page.keyboard.press('Enter');assert(await page.locator('.intelligence').getAttribute('open')!==null);assert.equal(await page.locator('.intelligence input,.intelligence button,.intelligence textarea').count(),0);await page.locator('.intelligence details>summary').click();await layout(page);await accessibility(page);await shot(page,`intelligence-${width}`);}
  scenes++;await context.close();
 }
 for(const width of [320,360,412]){const {page,context}=await open(width,'AFTER','GREEN','reduced');assert.equal(await page.locator('.mission').evaluate(e=>getComputedStyle(e).animationName),'none');await page.locator('.intelligence>summary').click();assert.equal(await page.locator('.fold-content').first().evaluate(e=>getComputedStyle(e).animationName),'none');await shot(page,`reduced-motion-${width}`);await context.close();}
 {
 const {page,context}=await open();await page.getByRole('button',{name:"I'll do this",exact:true}).click();assert.equal(await page.locator('dialog').count(),0);assert(await page.locator('.decision-feedback').innerText().then(t=>t.includes('preview only')));await page.getByRole('button',{name:'Undo preview'}).click();await page.getByRole('button',{name:'Record information'}).click();await shot(page,'record-chooser-360',false);await page.getByRole('button',{name:'Water',exact:true}).click();assert.equal(await page.locator('input[name=amount]').evaluate(e=>e===document.activeElement),true);await page.getByLabel('Amount (oz)').fill('0');assert.equal(await page.getByLabel('Amount (oz)').evaluate(e=>e.checkValidity()),false);await page.getByLabel('Amount (oz)').fill('8');await layout(page);await accessibility(page);await shot(page,'water-entry-360',false);await page.getByRole('button',{name:'Preview entry',exact:true}).click();assert(await page.getByRole('status').innerText().then(t=>t.includes('Nothing saved')));assert.equal(await page.locator('.record-trigger').evaluate(e=>e===document.activeElement),true);
 await page.getByRole('button',{name:'Record information'}).click();await page.getByRole('button',{name:'Check-in',exact:true}).click();assert.equal(await page.locator('dialog select').count(),5);await layout(page);await accessibility(page);await shot(page,'check-in-360',false);await page.keyboard.press('Escape');assert.equal(await page.locator('dialog').count(),0);assert.equal(await page.locator('.record-trigger').evaluate(e=>e===document.activeElement),true);
 await page.getByRole('button',{name:'Record information'}).click();for(let i=0;i<10;i++){await page.keyboard.press('Tab');assert(await page.evaluate(()=>document.querySelector('dialog').contains(document.activeElement)));}await page.keyboard.press('Escape');await context.close();
 }
 {const {page,context}=await open(360,'AFTER','RED');await page.getByRole('button',{name:'Not doing this',exact:true}).click();assert.equal(await page.locator('.decision-feedback').count(),0);await page.getByRole('button',{name:'Confirm preview decline'}).click();assert(await page.locator('.decision-feedback').innerText().then(t=>t.includes('Declined')));await context.close();}
 {const {page,context}=await open(360,'UNKNOWN','NO_READ');await page.getByRole('button',{name:'YES',exact:true}).click();assert.equal(await page.locator('[data-phase-row=QUICK_LOG]').count(),1);assert(await page.locator('.status-reading').innerText().then(t=>t.includes('NO READ')));await page.locator('.daily .fold>summary').click();await page.getByRole('button',{name:'MARK WORK ENDED'}).click();assert.equal(await page.locator('[data-phase-row=SHIFT_DOWN]').count(),1);await context.close();}
 for(const tab of ['TRAIN','BODY','MORE']){const {page,context}=await open(412,'AFTER','GREEN','tab='+tab);await layout(page);await accessibility(page);if(tab==='TRAIN'){assert.equal(await page.locator('.exercise-list details').count(),4);await page.getByRole('button',{name:'REDUCED',exact:true}).click();assert.equal(await page.locator('.exercise-list details').count(),2);}if(tab==='BODY'){await page.getByText('View sample records',{exact:true}).click();assert.equal(await page.locator('tbody tr').count(),7);}await shot(page,tab.toLowerCase()+'-412');await context.close();}
 for(const story of ['BEFORE','SHIFT','TRAINING','OFF']){const {page,context}=await open(412,story);await shot(page,'scenario-'+story.toLowerCase()+'-412');await context.close();}
 {const {page,context}=await open(1440);await layout(page);await accessibility(page);await shot(page,'desktop-today',false);await page.locator('.intelligence>summary').click();await shot(page,'desktop-intelligence');await context.close();}
 assert.deepEqual(errors,[],'Browser exceptions / storage access');assert.deepEqual(external,[],'External requests');writeFileSync(root+'verification.json',JSON.stringify({base,scenes,accessibilityScans:scans,screenshots:shots,browserErrors:errors,externalRequests:external,passed:true},null,2));console.log(JSON.stringify({scenes,accessibilityScans:scans,screenshots:shots,passed:true}));
}finally{await browser.close();}
